// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/enginegrpc/engine.proto

package enginegrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_internal_enginegrpc_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_enginegrpc_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_internal_enginegrpc_engine_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ConnectRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_internal_enginegrpc_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_enginegrpc_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_internal_enginegrpc_engine_proto_rawDescGZIP(), []int{1}
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_internal_enginegrpc_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_enginegrpc_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_internal_enginegrpc_engine_proto_rawDescGZIP(), []int{2}
}

func (x *DisconnectRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_internal_enginegrpc_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_enginegrpc_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_internal_enginegrpc_engine_proto_rawDescGZIP(), []int{3}
}

type ExecuteRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AppId           string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Token           string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	EndpointName    string                 `protobuf:"bytes,3,opt,name=endpoint_name,json=endpointName,proto3" json:"endpoint_name,omitempty"`
	Params          []byte                 `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	Credentials     map[string]string      `protobuf:"bytes,5,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Environment     string                 `protobuf:"bytes,6,opt,name=environment,proto3" json:"environment,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	RequestBodyHash string                 `protobuf:"bytes,8,opt,name=request_body_hash,json=requestBodyHash,proto3" json:"request_body_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_internal_enginegrpc_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_enginegrpc_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_internal_enginegrpc_engine_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ExecuteRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ExecuteRequest) GetEndpointName() string {
	if x != nil {
		return x.EndpointName
	}
	return ""
}

func (x *ExecuteRequest) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ExecuteRequest) GetCredentials() map[string]string {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *ExecuteRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ExecuteRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ExecuteRequest) GetRequestBodyHash() string {
	if x != nil {
		return x.RequestBodyHash
	}
	return ""
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	StatusCode    int32                  `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_internal_enginegrpc_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_enginegrpc_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_internal_enginegrpc_engine_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

var File_internal_enginegrpc_engine_proto protoreflect.FileDescriptor

const file_internal_enginegrpc_engine_proto_rawDesc = "" +
	"\n" +
	" internal/enginegrpc/engine.proto\x12\tengine.v1\"=\n" +
	"\x0eConnectRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x11\n" +
	"\x0fConnectResponse\"*\n" +
	"\x11DisconnectRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"\x14\n" +
	"\x12DisconnectResponse\"\x95\x03\n" +
	"\x0eExecuteRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12#\n" +
	"\rendpoint_name\x18\x03 \x01(\tR\fendpointName\x12\x16\n" +
	"\x06params\x18\x04 \x01(\fR\x06params\x12L\n" +
	"\vcredentials\x18\x05 \x03(\v2*.engine.v1.ExecuteRequest.CredentialsEntryR\vcredentials\x12 \n" +
	"\venvironment\x18\x06 \x01(\tR\venvironment\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\x12*\n" +
	"\x11request_body_hash\x18\b \x01(\tR\x0frequestBodyHash\x1a>\n" +
	"\x10CredentialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\t\x10\n" +
	"R\x0eretry_override\"`\n" +
	"\x0fExecuteResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode2\xe0\x01\n" +
	"\rEngineService\x12@\n" +
	"\aConnect\x12\x19.engine.v1.ConnectRequest\x1a\x1a.engine.v1.ConnectResponse\x12I\n" +
	"\n" +
	"Disconnect\x12\x1c.engine.v1.DisconnectRequest\x1a\x1d.engine.v1.DisconnectResponse\x12B\n" +
	"\aExecute\x12\x19.engine.v1.ExecuteRequest\x1a\x1a.engine.v1.ExecuteResponse0\x01B8Z6github.com/Usefused/cli/internal/enginegrpc;enginegrpcb\x06proto3"

var (
	file_internal_enginegrpc_engine_proto_rawDescOnce sync.Once
	file_internal_enginegrpc_engine_proto_rawDescData []byte
)

func file_internal_enginegrpc_engine_proto_rawDescGZIP() []byte {
	file_internal_enginegrpc_engine_proto_rawDescOnce.Do(func() {
		file_internal_enginegrpc_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_enginegrpc_engine_proto_rawDesc), len(file_internal_enginegrpc_engine_proto_rawDesc)))
	})
	return file_internal_enginegrpc_engine_proto_rawDescData
}

var file_internal_enginegrpc_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_enginegrpc_engine_proto_goTypes = []any{
	(*ConnectRequest)(nil),     // 0: engine.v1.ConnectRequest
	(*ConnectResponse)(nil),    // 1: engine.v1.ConnectResponse
	(*DisconnectRequest)(nil),  // 2: engine.v1.DisconnectRequest
	(*DisconnectResponse)(nil), // 3: engine.v1.DisconnectResponse
	(*ExecuteRequest)(nil),     // 4: engine.v1.ExecuteRequest
	(*ExecuteResponse)(nil),    // 5: engine.v1.ExecuteResponse
	nil,                        // 6: engine.v1.ExecuteRequest.CredentialsEntry
}
var file_internal_enginegrpc_engine_proto_depIdxs = []int32{
	6, // 0: engine.v1.ExecuteRequest.credentials:type_name -> engine.v1.ExecuteRequest.CredentialsEntry
	0, // 1: engine.v1.EngineService.Connect:input_type -> engine.v1.ConnectRequest
	2, // 2: engine.v1.EngineService.Disconnect:input_type -> engine.v1.DisconnectRequest
	4, // 3: engine.v1.EngineService.Execute:input_type -> engine.v1.ExecuteRequest
	1, // 4: engine.v1.EngineService.Connect:output_type -> engine.v1.ConnectResponse
	3, // 5: engine.v1.EngineService.Disconnect:output_type -> engine.v1.DisconnectResponse
	5, // 6: engine.v1.EngineService.Execute:output_type -> engine.v1.ExecuteResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_enginegrpc_engine_proto_init() }
func file_internal_enginegrpc_engine_proto_init() {
	if File_internal_enginegrpc_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_enginegrpc_engine_proto_rawDesc), len(file_internal_enginegrpc_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_enginegrpc_engine_proto_goTypes,
		DependencyIndexes: file_internal_enginegrpc_engine_proto_depIdxs,
		MessageInfos:      file_internal_enginegrpc_engine_proto_msgTypes,
	}.Build()
	File_internal_enginegrpc_engine_proto = out.File
	file_internal_enginegrpc_engine_proto_goTypes = nil
	file_internal_enginegrpc_engine_proto_depIdxs = nil
}
